import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import { UserDataProvider } from "@/context/UserProfileContext";
// import Providers from "@/components/Provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/auth";
import Providers from "@/components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // pick what you actually use
  variable: "--font-roboto", // optional but recommended
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <Providers session={session}>
          <UserDataProvider>{children}</UserDataProvider>
        </Providers>
  
      </body>
    </html>
  );
}
