import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import { UserDataProvider } from "@/context/UserProfileContext";
// import Providers from "@/components/Provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/auth";
import Providers from "@/components/Provider";
import Script from "next/script";
import ChatwootLoader from "./ChatwootLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // pick what you actually use
  variable: "--font-roboto", // optional but recommended
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={roboto.variable}>
      <body suppressHydrationWarning>
        <Providers session={session}>
          <UserDataProvider>{children}</UserDataProvider>
        </Providers>
        {/* <Script id="testing">
          {` (function(d,t) {
    var BASE_URL="http://192.168.100.110:3000";
    var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=BASE_URL+"/packs/js/sdk.js";
    g.async = true;
    s.parentNode.insertBefore(g,s);
    g.onload=function(){
      window.chatwootSDK.run({
        websiteToken: 'FfQhi5Mj1skDw4u4BsDCcg4z',
        baseUrl: BASE_URL
      })
    }
  })(document,"script");`}
        </Script> */}

        <ChatwootLoader />
      </body>
    </html>
  );
}

// alda tifn zhak xqmy
